config/routes.rb
Rails.application.routes.draw do
  resources :categories
  root "events#index"
  get "events/filter/:filter" => "events#index", as: :filter_events
  resources :events do
    resources :registrations
    resources :likes
  end

  resource :session, only: [ :new, :create, :destroy ]

  resources :users
  get "signup" => "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorization.rb
class Categorization < ApplicationRecord
  belongs_to :event
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categorizations, dependent: :destroy
  has_many :events, through: :categorizations

  validates :name, presence: true, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :registrations, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  validates :name, presence: true, uniqueness: true
  validates :location, presence: true

  validates :description, length: { minimum: 25 }

  validates :price, numericality: { greater_than_or_equal_to: 0 }

  validates :capacity, numericality: { only_integer: true, greater_than: 0 }

  validates :image_file_name, format: { with: /\w+\.(jpg|png)\z/i, message: "must be a JPG or PNG image" }

  before_save :set_slug

  scope :past, -> { where("starts_at < ?", Time.now).order("starts_at") }
  scope :upcoming, -> { where("starts_at > ?", Time.now).order("starts_at") }
  scope :free, -> { upcoming.where(price: 0.0).order(:name) }
  scope :recent, ->(max = 3) { past.limit(max) }

  def free?
    price.blank? || price.zero?
  end

  def soldout?
    (capacity - registrations.size) <= 0
  end

  def to_param
    slug
  end

  private
  def set_slug
    self.slug = name.parameterize
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :event
  belongs_to :user

  HOW_HEARD_OPTIONS = [
    "Newsletter",
    "Blog Post",
    "Twitter",
    "Web Search",
    "Friend/Coworker",
    "Other"
  ]

  validates :how_heard, inclusion: { in: HOW_HEARD_OPTIONS }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :registrations, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_events, through: :likes, source: :event

  has_secure_password

  validates :name, presence: true
  validates :email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  private
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def current_user?(user)
    current_user == user
  end

  helper_method :current_user?

  def require_signin
    unless current_user
      session[:intended_url] = request.url
      redirect_to new_session_url, alert: "Please sign in first!"
    end
  end

  helper_method :current_user

  def require_admin
    unless current_user.admin?
      redirect_to events_url, alert: "Unauthorized access!"
    end
  end

  def is_admin?
    current_user && current_user.admin?
  end

  helper_method :is_admin?
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_signin, except: [ :index, :show ]
  before_action :require_admin, except: [ :index, :show ]
  before_action :set_event, only: [ :show, :edit, :update, :destroy ]
  def index
    case params[:filter]
    when "past"
      @events = Event.past
    when "free"
      @events = Event.free
    when "recent"
      @events = Event.recent(params[:limit])
    else
      @events = Event.upcoming
    end
  end

  def show
    @likers = @event.likers
    @categories = @event.categories
    if current_user
      @liked = current_user.likes.find_by(event_id: @event.id)
    end
  end

  def edit
  end


  def update
    if @event.update(event_params)
      redirect_to event_path(@event), notice: "Event succesfully created!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: "Event succesfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy!
    redirect_to events_path
  end

  private
  def set_event
    @event = Event.find_by!(slug: params[:id])
  end
  def event_params
    params.require(:event).permit(:name, :description, :location, :price, :starts_at, :capacity, :image_file_name, category_ids: [])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_signin

  def create
    @event = Event.find_by!(slug: params[:event_id])
    @event.likes.create!(user: current_user)
    redirect_to @event
  end

  def destroy
    like = current_user.likes.find(params[:id])
    like.destroy

    event = Event.find_by!(slug: params[:event_id])
    redirect_to event
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to (session[:intended_url] || events_url), notice: "Welcome back, #{user.name}"
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Invalid email/password combination!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to events_url, status: :see_other, notice: "You're now signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signin, except: [ :new, :create ]
  before_action :require_correct_user, only: [ :edit, :update, :destroy ]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @registrations = @user.registrations
    @liked_events = @user.liked_events
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_param)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks for signing up!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_param)
      redirect_to @user, notice: "Account successfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to events_url, status: :see_other, alert: "Account successfully deleted!"
  end

  private
  def user_param
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to eventurl unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def price(event)
    if event.free?
       "Free"
    else
      number_to_currency(event.price, precision: 0)
    end
  end

  def day_and_time(event)
    event.starts_at.strftime("%B %d at %I:%M %P")
  end
end

app/helpers/likes_helper.rb
module LikesHelper
  def like_or_unlike_button(event, liked)
    if liked
     button_to "⭐️ Unlike", event_like_path(event, liked), method: :delete
    else
     button_to "⭐️ Like", event_likes_path(event)
    end
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
  def register_or_sold_out(event)
    if event.soldout?
      content_tag(:span, "Sold Out!", class: "sold-out")
    else
      link_to "Register!", new_event_registration_path(@event), class: "register"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%=  flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="flash alert">
    <%=  flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  Copyright 2025 &copy; <a href="https://awexe.com">Awexe Software Solution</a>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag('logo.png'), root_path %>
    <ul class="left">
      <li>
        <%= link_to "Upcoming", events_path %>
      </li>
      <li>
        <%= link_to "Past", filter_events_path(:past) %>
      </li>
      <li>
        <%= link_to "Free", filter_events_path(:free) %>
      </li>
      <li>
        <%= link_to "Recent", filter_events_path(:recent) %>
      </li>
    </ul>
    <ul class="right">
      <% if current_user %>
        <li>
          <%= link_to current_user.name, current_user %>
        </li>
        <li>
          <%= link_to "Sign Out", session_path, data: {turbo_method: :delete}, class: "button" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign In", new_session_path,class: "button"%>
        </li>
        <li>
          <%= link_to "Sign Up", signup_path , class: "button" %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Eventz" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="content">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
  <% if object.errors.any? %>
  <section class="errors">
    <h2>Oops! Your form could not be saved.</h1>
    <h3>Please correct the following <%= pluralize(object.errors.count, "error") %> </h2>
    <ul>
      <% object.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </section>
<% end %>